### ISSUE TITLE
reference between different asset administration shells

### ISSUE THREAD

**Issue by githublena** [admin-shell/aasx-package-explorer#35] opened 2020-06-22 14:35 UTC
is there a possibility within existing AASX Explorer to reference between different asset Administration shells in order to implement for example nestability of Shells or to make it possible one asset is able to have different asset Administration Shells across its lifecycle?

**Comment by BirgitBoss** [comment] 2020-08-24 07:53
It is possible to have more than one AAS for an asset: the asset has a unique id and is referenced by the AssetAdministrationShell-object.

Nestability of shells is not supported (by design decision), but what is supported are so-called composite I4.0 components, i.e. **composite assets**. These are modelled by creating a submodel and then creating **Entity** submodel elements. Via the RelationshipElement also relations between these entity objects can be modelled, e.g. partOf or connectedTo. An Entity may have its own AAS (self-managed) but this is not required.

Examples can be found in https://github.com/admin-shell/aasx-package-explorer/blob/master/builds/development/DataModelV2/build200518/sample-aasx.zip: see sample-docu-BOM.aasx or MTPsample.aasx

**Comment by BirgitBoss** [comment] 2020-12-01 19:27
I think this issue can be closed.

**Comment by BirgitBoss** [comment] 2020-12-05 13:53
I close the issue, for any new issues please go to admin-shell-io/aasx-package-explorer.

**Closed as completed** 2020-12-05 13:53 UTC
